---

- name: Automate Cisco ACI
  hosts: localhost
  connection: local
  gather_facts: false
  module_defaults:
    group/cisco.aci.all:
      host: "sandboxapicdc.cisco.com"
      username: "admin"
      password: "!v3G@!4@Y"
      validate_certs: false
  roles:
    - aci-automation
