---

- name: Automate Cisco ACI
  hosts: aci
  gather_facts: false
  pre_tasks:
    - name: Ensure ACI login data is provided via environment variables
      ansible.builtin.assert:
        that:
          - lookup('env', 'ACI_HOST') is defined
          - lookup('env', 'ACI_USERNAME') is defined
          - lookup('env', 'ACI_PASSWORD') is defined
          - lookup('env', 'ACI_VALIDATE_CERTS') is defined
        quiet: true
        fail_msg: "Provide login credentials, for example: 'export ACI_HOST=aci-api-endpoint'"
  roles:
    - aci-automation
