---

- name: Automate Cisco ACI
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Ensure required ACI connection environment variables are set
      ansible.builtin.assert:
        that:
          - lookup('env', 'ACI_HOST') | length > 0
          - lookup('env', 'ACI_USERNAME') | length > 0
          - lookup('env', 'ACI_PASSWORD') | length > 0
          - lookup('env', 'ACI_VALIDATE_CERTS') | length > 0
        quiet: true
        fail_msg: "Required ACI connection variables not set! Export the environment variables."
  roles:
    - apic_automation
