---

- name: Automate Cisco ACI
  hosts: aci
  connection: local
  gather_facts: false
  module_defaults:
    group/cisco.aci.all:
      host: "sandboxapicdc.cisco.com"
      username: "admin"
      password: "!v3G@!4@Y"
      validate_certs: false
  pre_tasks:
    - debug:
        msg:
          - "{{ inventory_dir }}"
          - "{{ inventory_file }}"
  roles:
    - aci-automation
